/**
 * Content access layer.
 *
 * Verbatim HTML bodies live in src/book/** and are imported raw at build time;
 * ordering/metadata come from the JSON manifests generated by the migration.
 */
import chaptersData from '../data/chapters.json';
import pagesData from '../data/pages.json';

const chapterHtml = import.meta.glob('../book/chapters/*.html', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;
const pageHtml = import.meta.glob('../book/pages/*.html', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;

function indexBySlug(map: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(map)) {
    const slug = key.split('/').pop()!.replace(/\.html$/, '');
    out[slug] = value;
  }
  return out;
}

const chapterBodies = indexBySlug(chapterHtml);
const pageBodies = indexBySlug(pageHtml);

export interface Chapter {
  slug: string;
  /** Chapter number, or null for lettered interludes (C / D / E♭). */
  number: number | null;
  title: string;
  dateline: string;
  volume: number;
  interlude?: boolean;
}
export interface PageMeta {
  slug: string;
  title: string;
}

export const CHAPTERS = chaptersData as Chapter[];
export const PAGES = pagesData as PageMeta[];

export const TOTAL_CHAPTERS = CHAPTERS.length;

export function getChapterHtml(slug: string): string {
  return chapterBodies[slug] ?? '';
}

export function getChapterNeighbors(slug: string): { prev: Chapter | null; next: Chapter | null } {
  const i = CHAPTERS.findIndex((c) => c.slug === slug);
  return {
    prev: i > 0 ? CHAPTERS[i - 1] : null,
    next: i >= 0 && i < CHAPTERS.length - 1 ? CHAPTERS[i + 1] : null,
  };
}

export function getPageHtml(slug: string): string {
  return pageBodies[slug] ?? '';
}
export function getPageMeta(slug: string): PageMeta | undefined {
  return PAGES.find((p) => p.slug === slug);
}

const ROMAN = ['', 'One', 'Two', 'Three', 'Four', 'Five'];
export function volumeName(n: number): string {
  return ROMAN[n] ?? String(n);
}
